//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UchP11
{
    using System;
    using System.Collections.Generic;
    
    public partial class Istoriya_pokupok
    {
        public int id { get; set; }
        public int tovar { get; set; }
        public int kolvo { get; set; }
        public System.DateTime date { get; set; }
    
        public virtual Tovar Tovar1 { get; set; }
    }
}
