//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UchP11
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tovar
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Tovar()
        {
            this.Istoriya_pokupok = new HashSet<Istoriya_pokupok>();
        }
    
        public int id { get; set; }
        public string name { get; set; }
        public int stoimost { get; set; }
        public string opisanie { get; set; }
        public string main_photo { get; set; }
        public int proizvoditel { get; set; }
        public bool actualnost { get; set; }
    
        public string ActualText
        {
            get
            {
                return (actualnost) ? "Актуален" : "Не актуален";
            }        
        }

        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Istoriya_pokupok> Istoriya_pokupok { get; set; }
        public virtual Proizvoditel Proizvoditel1 { get; set; }
    }
}
